name: medmnist_resnet50_active_learning
description: "Active learning loop with ResNet-50 on MedMNIST dataset."

hyperparameters:
  learning_rate:
    type: double
    minval: 0.0001
    maxval: 0.1
  weight_decay:
    type: double
    minval: 0.00001
    maxval: 0.0005
  batch_size:
    type: int
    minval: 32
    maxval: 128
  initial_labeled_size:
    type: int
    minval: 3000
    maxval: 6000
  mc_dropout_passes:
    type: int
    minval: 2
    maxval: 7
  samples_to_label:
    type: int
    minval: 3000
    maxval: 4500

entrypoint: python3 model_def.py

project: Active_learning

workspace: Determined_AI_Hackathon

checkpoint_storage:
  type: shared_fs
  host_path: pytorch_model
  save_trial_best: 1
  save_trial_latest: 1

resources:
  slots_per_trial: 1

searcher:
  name: adaptive_asha
  metric: val_loss
  smaller_is_better: true
  max_length:
    epochs: 20
  max_trials: 10
